# Generated by Django 5.1.5 on 2025-01-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womeninfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenmodel',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='womenmodel',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
